# Generated by Django 5.2.7 on 2026-02-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationroletarget',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_targets', to='notification.notification'),
        ),
        migrations.AddField(
            model_name='notificationroletarget',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_targets', to='auth.group', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='notification.notification'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_states', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='notificationroletarget',
            constraint=models.UniqueConstraint(fields=('notification', 'role'), name='uniq_notification_role_target'),
        ),
        migrations.AddConstraint(
            model_name='notificationuser',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='uniq_notification_user'),
        ),
    ]
