# Generated by Django 5.2.7 on 2026-02-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statetransitionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transition_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statetransitionlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='uq_common_tag_type_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('type', 'slug'), name='uq_common_tag_type_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='statetransitionlog',
            index=models.Index(fields=['content_type', 'object_id'], name='state_log_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='statetransitionlog',
            index=models.Index(fields=['created_at'], name='state_log_created_idx'),
        ),
    ]
