# Generated by Django 5.2.7 on 2026-02-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('admin', 'Admin'), ('investor', 'Investor'), ('startup', 'Startup')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Workflow stage',
                'verbose_name_plural': 'Workflow stages',
                'ordering': ['scope', 'code'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'code'), name='uniq_workflow_stage_scope')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('admin', 'Admin'), ('investor', 'Investor'), ('startup', 'Startup')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='common.workflowstage')),
            ],
            options={
                'verbose_name': 'Workflow state',
                'verbose_name_plural': 'Workflow states',
                'ordering': ['scope', 'stage__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('action', models.CharField(blank=True, help_text='Optional decision action (e.g., approve/reject).', max_length=16)),
                ('requires_admin', models.BooleanField(default=False)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='common.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='common.workflowstate')),
            ],
            options={
                'verbose_name': 'Workflow transition',
                'verbose_name_plural': 'Workflow transitions',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='uniq_workflow_state_scope'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_workflow_transition_code'),
        ),
    ]
