# Generated by Django 5.2.7 on 2026-02-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_perms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userobjectpermission',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'perm_codename'), name='uniq_user_object_perm'),
        ),
    ]
